SET S3_BUCKET = 'xxxxxx';
SET STORAGE_AWS_ROLE_ARN = 'xxxxxx';
SET INTEGRATION_NAME = 'correction_s3_integration';

-- new dev account
CREATE OR REPLACE STORAGE INTEGRATION identifier($INTEGRATION_NAME)
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = 'S3'
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = $STORAGE_AWS_ROLE_ARN
  STORAGE_ALLOWED_LOCATIONS = ($S3_BUCKET);

DESC INTEGRATION identifier($INTEGRATION_NAME);



