"""empty message

Revision ID: 0fe1b9298b97
Revises: 8ee35364fc1f
Create Date: 2026-08-21 19:15:17.867801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fe1b9298b97'
down_revision: Union[str, Sequence[str], None] = '8ee35364fc1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter',
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('length', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meter')
    # ### end Alembic commands ###
