"""meter-readings-corrected

Revision ID: 4f35658be104
Revises: 2c1346aa3935
Create Date: 2026-08-22 16:58:20.321214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f35658be104'
down_revision: Union[str, Sequence[str], None] = '2c1346aa3935'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meter_reading_corrected',
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('length', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('measured_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meter_reading_corrected')
    # ### end Alembic commands ###
