"""calibration-control

Revision ID: 74b45969f8e6
Revises: c5f0c215120f
Create Date: 2026-08-23 00:05:36.601191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74b45969f8e6'
down_revision: Union[str, Sequence[str], None] = 'c5f0c215120f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calibration',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('calibration_type', sa.Enum('LINEAR', 'PARABOLIC', 'PIECEWISE_LINEAR_4', name='calibrationtype', native_enum=False), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calibration')
    # ### end Alembic commands ###
